### ISSUE TITLE
Investigate how to integrate Zoho information

### ISSUE THREAD

**Issue by mtraverso3** [stevensblueprint/c4p-payload#20]
We might need some custom components that display the Zoho information.

**Comment by brandonyen** [comment]
to do:
- find out if there are any costs associated with api calls for zoho (do we need to host a server to store api data for a period of time?)
- create custom component for each of the desired metrics

**Comment by brandonyen** [comment]
update:

- should be no cost associated if we are only calling the API once every 15-30 mins. access tokens expire every hour, but we can use a refresh token (which does not expire until revoked) to get a new access token every 15-30 mins (or however often we want to refresh the stats). Either that or we can call for an update every time someone accesses the website.
